stages:
  load_data:
    cmd: python src/load_data.py --config=parameters.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_given/Count.csv
    outs:
      - data/raw/Count.csv

  split_data:
    cmd: python src/split_data.py --config=parameters.yaml
    deps:
      - src/split_data.py
      - data/raw/Count.csv
    outs:
      - data/process/train_count.csv
      - data/process/test_count.csv