base:
  project: operationcount-multivariate-timeseries
  target_col: TARGET

data_source:
  azblob_source: data_given/Count.csv

load_data:
  raw_dataset_csv: data/raw/Count.csv

split_data:
  train_path: data/process/train_count.csv
  test_path: data/process/test_count.csv
  train_size: 0.8

estimator:
  VAR:
    params:
      steps:3

model_dir: saved_model
